import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Box } from "@mui/material";
import { MainNav } from "@/components/Layout/MainNav";
import ThemeProviderApp from "@/components/Layout/ThemeProvider";

export const metadata: Metadata = {
  title: "Technical Test",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={roboto.className}
      suppressHydrationWarning={true}
    >
      <body>
        <ThemeProviderApp>
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              alignItems: "center",
              height: "100vh",
            }}
          >
            <MainNav />
            <Box
              sx={{
                height: "100%",
                display: "flex",
                flexDirection: "column",
                width: "90%",
                padding: 2,
                marginTop: 2,
              }}
            >
              {children}
            </Box>
          </Box>
          {/* <Box display="flex" flexDirection="column" minHeight="100vh">
            <MainNav />
            <Box sx={{ flex: 1, m: 4 }}>
              {children}
              </Box>
          </Box> */}
        </ThemeProviderApp>
      </body>
    </html>
  );
}
